version: '2'
services:
    cryptominerindonesia-app:
        image: cryptominerindonesia
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cryptominerindonesia-mysql:3306/cryptominerindonesia?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cryptominerindonesia-mysql:
        extends:
            file: mysql.yml
            service: cryptominerindonesia-mysql
